### ISSUE TITLE
cannot install by cocoapod

### ISSUE THREAD

**Issue by ghost** [roycms/RCalendarPicker#2]
thanks for sharing this nice framework!
but cannot install by using cocoapod :(

**Comment by ghost** [comment]
does this code work correctly? it doesn't seem to work for me

line 94, 95 in .podspec
s.source_files  = "RCalendarPickerClass/*.*"
s.source_files  = "RCalendarPickerClass/*/*.*"

**Comment by roycms** [comment]
# Manual installation  
1.copy  "RCalendarPickerClass/" To your own project
 
2.Make sure your project installation  pod install 
```
 pod 'Masonry'
 pod 'RGB'
```

The hope can help you

### Very depressed, I do not know why it's been so long since I had submitted, in cocoapods website has been around for project, but the search is less than so now can only be manually import. The following addresses can be proved that can have a know how to solve the @ I thank you very much!  
https://cocoapods.org/pods/RCalendarPicker

**Comment by ghost** [comment]
ok, i'll try manual installation

But option of installing by cocoapod is so nice to have, 
so i recommend you try cocoapod again.

Also, let me say again that  i could only install the file in RCalendarPickerClass/ * / *, not the .h files or .m files in the RCalendarPickerClass/ *  when i use cocoapod. and i guess the reason is you write the .podspec file to do so. (-> "source_files": "RCalendarPickerClass/ * / * . *") 

btw, i actually don't exactly understand  what u say in the above , so i'm sorry if i'm wrong...

**Comment by roycms** [comment]
There are no mistakes. Podspec , verify through, pod push is a success, is the pod search less than, don't know why, according to https://cocoapods.org/pods/RCalendarPicker website have

**Comment by ghost** [comment]
Are you sure that you successfully committed your ver. 1.1.4 to Cocoapod?

It seems Cocoapod only have ver. 1.1.3 ...

**Comment by ghost** [comment]
Now that you changed .podspec file, we can install this framework by using the below code.

pod 'RCalendarPicker',  :git => 'https://github.com/roycms/RCalendarPicker.git'
